### ISSUE TITLE
Safari 13 is not supported

### ISSUE THREAD

**Issue by martindzejky** [xeroxinteractive/browserslist-browserstack#366]
Hello 👋 

Browserstack supports Safari 13 on OSX Catalina. However, when I provide a browserslist query to `browserslist-browserstack` equal to this: `safari 13`, it returns an empty list of browsers.

## Minimal script to reproduce

```
const getCapabilities = require('browserslist-browserstack').default;

(async function() {

    const browsers = await getCapabilities({
        browserslist: {
            queries: [
                'safari 13'
            ]
        }
    });

    browsers.forEach(b =>
        console.log(`${b.os} ${b.os_version}, ${b.browser} ${b.browser_version}`)
    );

})();
```

## Expected result 

The script should print `OS X Catalina, safari 13.1`.

## Current result

The script does not print anything, no browser is selected.

**Comment by AndrewLeedham** [comment]
Hi @martindzejky 

Thanks for raising the issue. I believe this is because BrowserStack only supports `13.1` and not `13.0`, and the browserslist query `safari 13` only returns `safari 13`. To fix this you will likely need to do 2 things:
1. Use the query `safari >= 13` perhaps even `safari >= 13 && safari < 14`.
2. Make sure the browserslist stats are up-to-date by running `npx browserslist@latest --update-db`

**Comment by martindzejky** [comment]
Thanks for the quick response! Running `npx browserslist@latest --update-db` helped.
